Fix gocyclo lint error for internal/lvmd
topolvm/topolvm pull request #1001
Opened 2024-12-20 09:14 UTC by toshipp

issue: #853

2024-12-20 09:14 UTC, toshipp commented
This depends on #999.

2025-01-20 02:42 UTC, peng225 approved these changes

2025-01-21 11:20 UTC, satoru-takeuchi requested changes
Almost all changes looks file. Just one minor nit.

2025-01-23 00:35 UTC, peng225 approved these changes

2025-01-23 00:53 UTC, satoru-takeuchi approved these changes

2025-01-23 00:53 UTC, merged