Add minimum image
topolvm/topolvm pull request #236
Opened 2021-01-03 17:02 UTC by bells17

2021-01-14 06:04 UTC, toshipp requested changes

2021-01-14 06:04 UTC, toshipp commented on Dockerfile
>  # CSI sidecar
This is not needed.

2021-01-14 08:29 UTC, llamerada-jp commented
On a side note would you update the URL to quay.io in the bottom of README.md ?
New URL is `https://quay.io/organization/topolvm`

2021-01-17 11:43 UTC, bells17 commented on Dockerfile
>  # CSI sidecar
Thanks. I removed it.

2021-01-17 11:44 UTC, bells17 commented
https://github.com/topolvm/topolvm/pull/236#issuecomment-760017458
I updated the links.

2021-01-17 11:44 UTC, bells17 commented
@toshipp @llamerada-jp Hi, I updated. Could you review this again?

2021-01-18 00:20 UTC, toshipp approved these changes
LGTM

2021-01-19 02:37 UTC, llamerada-jp requested changes

2021-01-19 02:37 UTC, llamerada-jp commented on Dockerfile.with-sidecar
> +FROM golang:1.13-buster AS build-env
Please use golang 1.15 as the PR that updates golang has been merged recently.

https://github.com/topolvm/topolvm/blob/adcd4c9fd4ba26e24d1ee130a0e28646350ce7ab/Dockerfile#L2

2021-01-19 02:37 UTC, llamerada-jp commented on Dockerfile.with-sidecar
> +FROM ubuntu:18.04
Please use ubuntu 20.04 as the PR that updates ubuntu has been merged recently.

https://github.com/topolvm/topolvm/blob/adcd4c9fd4ba26e24d1ee130a0e28646350ce7ab/Dockerfile#L13

2021-01-20 05:02 UTC, toshipp approved these changes
LGTM

2021-01-22 01:20 UTC, llamerada-jp approved these changes
LGTM

2021-01-22 01:20 UTC, merged