Purge official sidecar images from e2e
topolvm/topolvm pull request #249
Opened 2021-01-20 09:10 UTC by tapih

Signed-off-by: Hiroshi Muraoka <h.muraoka714@gmail.com>

2021-01-27 02:28 UTC, toshipp submitted a review, later dismissed
LGTM

2021-01-27 07:44 UTC, llamerada-jp requested changes

2021-01-27 07:44 UTC, llamerada-jp commented on e2e/Makefile
> +	make -f ../csi-sidecars.mk OUTPUT_DIR=tmpbin
```suggestion
	$(MAKE) -f ../csi-sidecars.mk OUTPUT_DIR=tmpbin
```

2021-01-27 08:17 UTC, llamerada-jp approved these changes
LGTM

2021-01-28 00:17 UTC, toshipp approved these changes

2021-01-28 00:17 UTC, merged