wip
topolvm/topolvm pull request #254
Opened 2021-01-28 09:54 UTC by tapih

Signed-off-by: H.Muraoka <hiroshi-muraoka@cybozu.co.jp>

2021-01-28 09:57 UTC, ymmt2005 commented on docs/maintenance.md
> +### Check release notes
```suggestion
## Check release notes
```

Please adjust other titles as well.

2021-02-02 04:57 UTC, ymmt2005 requested changes

2021-02-02 04:57 UTC, ymmt2005 commented on docs/maintenance.md
> +In case we update the version of the CSI spec written in `Makefile`, we should regenerate the gRPC schema with the protobuf file corresponding to the CSI spec version.
To update **CSI** version, we need to update `CSI_VERSION` in Makefile, and run the following commands:

```console
$ make csi.proto
$ make generate 
```

2021-02-02 07:41 UTC, ymmt2005 approved these changes
LGTM

2021-02-02 09:18 UTC, toshipp submitted a review, later dismissed
LGTM.
I'm waiting for @llamerada-jp 's review before merge.

2021-02-03 01:50 UTC, llamerada-jp approved these changes
LGTM

2021-02-03 01:56 UTC, toshipp approved these changes

2021-02-03 04:23 UTC, merged