add a note about host's kernel to supported environments
topolvm/topolvm pull request #262
Opened 2021-02-24 09:18 UTC by llamerada-jp

Signed-off-by: Yuji Ito <llamerada.jp@gmail.com>

2021-02-25 00:53 UTC, toshipp requested changes

2021-02-25 00:53 UTC, toshipp commented on README.md
> +  The host's Linux Kernel must be v4.9 or later which supports `rmapbt` and `reflink`, if you use xfs filesystem with an official docker image.
It seems some spaces are required for proper rendering.

2021-02-25 02:12 UTC, toshipp approved these changes

2021-02-26 01:13 UTC, ymmt2005 approved these changes
LGTM

2021-02-26 01:13 UTC, merged