lvmd daemonset test
topolvm/topolvm pull request #265
Opened 2021-02-28 09:17 UTC by bells17

2021-03-16 09:58 UTC, toshipp requested changes
I think some rework is needed, but the outline is good.

I see directory name `kubeadm` is used, but you use minikube, is it missed to correct?

2021-03-16 09:58 UTC, toshipp commented on e2e/Makefile
> +	go build -o build/lvmd ../pkg/lvmd
Is it necessary?

2021-03-16 09:58 UTC, toshipp commented on e2e/Makefile
> +	$(SUDO) cp -f kubeadm/scheduler-config-$(TEST_KUBERNETES_SCHEDULER_VERSION).yaml /var/lib/scheduler/scheduler-config.yaml
It seems that scheduler policy and config are the same config and policy for daemonset in the e2e directory.
Would you explain any reason to copy them?

2021-03-16 09:58 UTC, toshipp commented on e2e/manifests/overlays/daemonset-lvmd/controller.yaml
> +---
I recognize this file is the same as common/controller.yaml except for node selector.
Kustomize supports deletion for yaml fragment, using `$delete` is clean manner, IMO.
see https://github.com/kubernetes-sigs/kustomize/blob/master/examples/inlinePatch.md

2021-03-16 09:58 UTC, toshipp commented on e2e/manifests/overlays/daemonset-lvmd/node.yaml
> +            path: /tmp/topolvm/lvmd_lvmd
This can be replaced by kustomize patch. so it is not necessary for entire content coping.

2021-03-16 09:58 UTC, toshipp commented on e2e/manifests/overlays/daemonset-lvmd/scheduler.yaml
> +apiVersion: apps/v1
This is the same as daemonset manifest, so don't copy but refer daemonset manifest from kustomization.yaml.

2021-03-16 09:58 UTC, toshipp commented on e2e/node_test.go
> +			if len(podlist.Items) != count {
I assume this test checks topolvm-node should be deployed on all nodes,
so check if pod number equals worker node number.

2021-03-16 09:58 UTC, toshipp commented on e2e/publish_test.go
> +		lvYaml := []byte(lvString)
use fmt.Sprintf.

2021-03-17 04:27 UTC, satoru-takeuchi requested changes

2021-03-17 04:27 UTC, satoru-takeuchi commented on e2e/Makefile
> +	$(SUDO) vgcreate -y node-lvmd-myvg1 $$($(SUDO) losetup -j $(BACKING_STORE)/backing_store_lvmd_1 | cut -d: -f1);
Is there any strong reason to use node-lvmd-myvgXX for vg names? Just using node-myvg1 as non-daemonset tests looks simpler.

2021-03-29 11:10 UTC, bells17 commented
Sorry, I can't resolve the CI tests error and it looks mistook my `git rebase`.
So I created the new PR(#265) instead of this PR.

2021-03-29 11:10 UTC, closed without merging