add a note for example to suggest tagged version
topolvm/topolvm pull request #266
Opened 2021-03-01 04:21 UTC by llamerada-jp

Signed-off-by: Yuji Ito <llamerada.jp@gmail.com>

2021-03-01 08:12 UTC, toshipp submitted a review, later dismissed
LGTM

2021-03-02 01:13 UTC, satoru-takeuchi requested changes

2021-03-02 01:13 UTC, satoru-takeuchi commented on example/README.md
> +$ git checkout refs/tags/v0.7.0
git checkout v0.7.0

2021-03-02 01:38 UTC, satoru-takeuchi approved these changes

2021-03-02 01:52 UTC, toshipp approved these changes

2021-03-02 01:58 UTC, satoru-takeuchi approved these changes

2021-03-02 03:13 UTC, merged