Modify to use embed package instated of raw string literals
topolvm/topolvm pull request #288
Opened 2021-04-02 15:13 UTC by bells17

ref: https://github.com/topolvm/topolvm/pull/285#discussion_r603927908
I modified to use embed package instead of raw string literals.

2021-04-05 00:45 UTC, toshipp commented on e2e/testdata/e2e/node-capacity-pvc2.yaml
> +  storageClassName: topolvm-provisioner
Would you add a new line?

2021-04-05 00:52 UTC, toshipp requested changes

2021-04-05 00:52 UTC, toshipp commented on e2e/testdata/hook/ephemeral-volume-pod-with-pvc.yaml
> +          claimName: local-pvc1
Would you add a newline?

2021-04-05 09:42 UTC, llamerada-jp commented
No additional comment. Would you reflect the comments by @toshipp

2021-04-06 16:30 UTC, bells17 commented
@toshipp @llamerada-jp Thank you for your review. I fixed the points of your comment.
Would you check this PR again?

2021-04-07 01:00 UTC, toshipp approved these changes
LGTM

2021-04-07 01:00 UTC, llamerada-jp approved these changes
LGTM

2021-04-07 01:01 UTC, merged