Bump chart version to 3.0.0
topolvm/topolvm pull request #366
Opened 2021-09-13 05:00 UTC by cupnes

2021-09-13 08:47 UTC, toshipp requested changes

2021-09-13 08:47 UTC, toshipp commented on charts/topolvm/CHANGELOG.md
> +[3.0.0]: https://github.com/topolvm/topolvm/compare/topolvm-chart-v2.1.0...topolvm-chart-v3.0.0
```suggestion
[3.0.0]: https://github.com/topolvm/topolvm/compare/topolvm-chart-v2.1.1...topolvm-chart-v3.0.0
```

2021-09-14 00:47 UTC, cupnes commented on charts/topolvm/CHANGELOG.md
> +[3.0.0]: https://github.com/topolvm/topolvm/compare/topolvm-chart-v2.1.0...topolvm-chart-v3.0.0
Fixed in 50bad83 .

2021-09-14 00:49 UTC, toshipp approved these changes

2021-09-15 00:58 UTC, llamerada-jp approved these changes

2021-09-16 04:02 UTC, merged