Update chart settings.
topolvm/topolvm pull request #370
Opened 2021-09-29 06:30 UTC by cupnes

- add pod disruption budget
- add updateStrategy for lvmd and topolvm-node
- add priorityClass

Signed-off-by: Yuma Ogami <yuma-ogami@cybozu.co.jp>

2021-09-29 06:43 UTC, toshipp approved these changes

2021-09-29 07:17 UTC, toshipp approved these changes

2021-09-30 02:15 UTC, llamerada-jp requested changes

2021-09-30 02:15 UTC, llamerada-jp commented on charts/topolvm/templates/controller/poddisruptionbudget.yaml
> +{{- if or .Values.controller.podDisruptionBudget.enabled }}
```suggestion
{{- if .Values.controller.podDisruptionBudget.enabled }}
```

2021-09-30 02:15 UTC, llamerada-jp commented on charts/topolvm/templates/scheduler/poddisruptionbudget.yaml
> +{{- if or .Values.scheduler.podDisruptionBudget.enabled }}
```suggestion
{{- if .Values.scheduler.podDisruptionBudget.enabled }}
```

2021-09-30 02:15 UTC, llamerada-jp commented on charts/topolvm/templates/priorityclass.yaml
> +{{- if or .Values.priorityClass.enabled }}
```suggestion
{{- if .Values.priorityClass.enabled }}
```

2021-09-30 02:15 UTC, llamerada-jp commented on charts/topolvm/CHANGELOG.md
> +- add PDB/updateStrategy/priorityClass (#370)
Has this PR not been released yet?

2021-09-30 02:38 UTC, toshipp approved these changes

2021-09-30 02:56 UTC, satoru-takeuchi approved these changes

2021-10-01 02:33 UTC, llamerada-jp approved these changes

2021-10-01 04:06 UTC, merged