Support Kubernetes v1.23
topolvm/topolvm pull request #431
Opened 2022-01-28 07:58 UTC by peng225

issue: topolvm/topolvm#418
Signed-off-by: Shinya Hayashi <shinya-hayashi@cybozu.co.jp>

2022-02-03 02:54 UTC, llamerada-jp requested changes
Would you update here to 1.17 form 1.16?
https://github.com/topolvm/topolvm/blob/v0.10.4/example/Vagrantfile#L21

2022-02-03 03:32 UTC, llamerada-jp commented
Would you regenerate *.pg.go files using updated protoc command.

2022-02-03 04:38 UTC, llamerada-jp requested changes

2022-02-03 04:38 UTC, llamerada-jp commented on charts/topolvm/Chart.yaml
> +    version: 1.7.0
Could you modify `charts/topolvm/README.md.gotmpl` and `deploy/README.md` to update version in documents.

2022-02-03 04:38 UTC, llamerada-jp commented on docs/proposals/multiple-volumegroups.md
> +  - [Ephemeral Inline Volume (**deprecated**)](#ephemeral-inline-volume-deprecated)
Would you revert the changes in this file? Because this document is a proposal.

2022-02-03 07:38 UTC, llamerada-jp approved these changes
LGTM

2022-02-03 08:49 UTC, peng225 commented on go.mod
>  	github.com/pseudomuto/protoc-gen-doc v1.4.1
@cupnes 
Sorry, I change the protoc-gen-doc version to v1.5.0.

2022-02-04 00:06 UTC, llamerada-jp approved these changes

2022-02-04 00:11 UTC, cupnes approved these changes

2022-02-04 01:04 UTC, merged