Bump chart version to 4.0.1
topolvm/topolvm pull request #436
Opened 2022-02-04 04:37 UTC by peng225

2022-02-04 08:40 UTC, cupnes approved these changes

2022-02-04 09:06 UTC, llamerada-jp requested changes
[This PR](https://github.com/topolvm/topolvm/pull/427)'s goal is to stabilize the test but is also including changes for the helm template. So would you add the record of it for the changelog?

2022-02-07 04:01 UTC, llamerada-jp approved these changes

2022-02-07 04:04 UTC, cupnes approved these changes

2022-02-07 04:04 UTC, merged