doc: Add design doc for thin-lv clones
topolvm/topolvm pull request #447
Opened 2022-03-16 09:17 UTC by Yuggupta27

Add design document to allow the creation of PVC-PVC clones
for PVCs backed by thinly-provisioned logical volumes.

Signed-off-by: Yug Gupta <yuggupta27@gmail.com>

2022-07-06 08:25 UTC, cupnes requested changes
Please make some corrections.

2022-07-14 04:59 UTC, Yuggupta27 commented
Thanks for the review @cupnes! Updated accordingly.
Also, attempted to address review comments from https://github.com/topolvm/topolvm/pull/446 here too.
Please let me know if I missed anything. Thanks!

2022-07-15 07:40 UTC, cupnes approved these changes

2022-07-20 02:07 UTC, satoru-takeuchi reviewed
I don't have an additional comment than [this](https://github.com/topolvm/topolvm/pull/447#discussion_r923203567). Please reflect this.

2022-07-20 02:11 UTC, satoru-takeuchi approved these changes

2022-07-20 03:56 UTC, Yuggupta27 commented on docs/proposals/thin-lv-clone.md
> +    $ lvchange -ay -K VG0/thinsnap
Thanks! Updated :+1:

2022-07-20 04:20 UTC, satoru-takeuchi approved these changes

2022-07-20 04:22 UTC, cupnes approved these changes

2022-07-20 04:22 UTC, merged