Add flag to disable cert-manager CRs
topolvm/topolvm pull request #451
Opened 2022-03-23 16:20 UTC by ooraini

Fixes #450

2022-03-24 09:26 UTC, toshipp commented
I think it is better to omit all cert-manager resources if the `webhook.caBundle` is specified because there is no meaningful use case where `webhook.caBundle` is used but `webhook.cert-manager` is set to `true` or  `webhook.caBundle` is not used but `webhook.cert-manager` is set to `false`.

2022-03-24 11:51 UTC, ooraini commented
@toshipp That makes a lot of sense. Will update soon.

2022-03-24 12:18 UTC, ooraini commented
@toshipp done.

2022-03-25 00:53 UTC, toshipp requested changes
@ooraini Looks good expect minor cosmetics. But I found a flaky CI issue, the test for the PR failed. I will fix it soon, please wait a while.

2022-03-25 00:53 UTC, toshipp commented on deploy/README.md
> -1. Prepare PEM encoded self-signed certificate and key files.
These trailing spaces are needed to add a new line. Could you revert it?

2022-03-25 09:07 UTC, daichimukai submitted a review, later dismissed

2022-03-30 09:06 UTC, toshipp commented
@ooraini I had stabilized CI via #452. Could you please rebase this branch?

2022-03-30 09:40 UTC, ooraini commented
@toshipp rebased

2022-03-30 11:20 UTC, toshipp approved these changes
LGTM

2022-03-31 08:19 UTC, daichimukai approved these changes

2022-03-31 08:19 UTC, merged