Modified to use ghcr.io as a container registry
topolvm/topolvm pull request #464
Opened 2022-04-12 17:10 UTC by bells17

#455

2022-04-13 09:51 UTC, toshipp commented on README.md
> +Docker images are available on [ghcr.io](https://github.com/orgs/topolvm/packages)
Please add a note that images on quay.io are now deprecated and will be unavailable in the future.

2022-04-14 00:58 UTC, toshipp requested changes

2022-04-14 00:58 UTC, toshipp commented on README.md
> +**Please note that [the images on quay.io](https://quay.io/organization/topolvm) is currently deprecated and will no longer be available in the future.**
```suggestion
**Please note that [the images on quay.io](https://quay.io/organization/topolvm) are currently deprecated and will no longer be available in the future.**
```

2022-04-14 02:15 UTC, toshipp approved these changes

2022-04-14 07:46 UTC, llamerada-jp approved these changes
LGTM

2022-04-14 07:46 UTC, llamerada-jp commented on .github/workflows/release.yaml
> +      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USER }} --password-stdin
memo:
We can login to ghcr using GITHUB_TOKEN according to the following document.
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry

2022-04-14 07:46 UTC, merged