additional metric for thin pools
topolvm/topolvm pull request #537
Opened 2022-07-22 15:07 UTC by nbalacha

Adds a metric to track the available overprovisioned bytes
for a thin pool.

Signed-off-by: N Balachandran <nibalach@redhat.com>

2022-08-02 00:19 UTC, llamerada-jp requested changes
Could you please add documents about metrics in `topolvm-node.md`?

2022-08-03 00:25 UTC, llamerada-jp commented
Would you please rebase to avoid CI failure?
ref: https://github.com/topolvm/topolvm/pull/542

2022-08-03 12:05 UTC, nbalacha commented
> Could you please add documents about metrics in `topolvm-node.md`?

Done.

2022-08-03 12:06 UTC, nbalacha commented
> Would you please rebase to avoid CI failure? ref: #542

Done.

2022-08-05 00:12 UTC, llamerada-jp approved these changes
LGTM

2022-08-05 00:38 UTC, satoru-takeuchi approved these changes

2022-08-05 00:38 UTC, merged