docs: fix incorrect flag description
topolvm/topolvm pull request #556
Opened 2022-08-23 08:39 UTC by pluser

Changed to explain that adding --ignore-daemonsets will allow pods to be
evicted. The explanation was the other way around.

Reported by nonylene at Slack.

Signed-off-by: ESASHIKA Kaoru <kaoru-esashika@cybozu.co.jp>

2022-08-24 00:34 UTC, peng225 requested changes

2022-08-24 00:34 UTC, peng225 commented on docs/user-manual.md
> +    `--ignore-daemonsets=true` allows the commands to succeed even if pods managed by daemonset exist (e.g. topolvm-node).
```suggestion
    `--ignore-daemonsets=true` allows the command to succeed even if pods managed by daemonset exist (e.g. topolvm-node).
```

2022-08-24 00:34 UTC, peng225 commented on docs/user-manual.md
> +   `--ignore-daemonsets=true` allows the commands to succeed even if pods managed by daemonset exist (e.g. topolvm-node).
```suggestion
   `--ignore-daemonsets=true` allows the command to succeed even if pods managed by daemonset exist (e.g. topolvm-node).
```

2022-08-24 09:54 UTC, toshipp approved these changes

2022-08-25 05:00 UTC, peng225 approved these changes

2022-08-25 05:01 UTC, merged