feat: add args for controller, node, scheduler, lvdm to helm chart
topolvm/topolvm pull request #576
Opened 2022-10-05 10:08 UTC by maxime1907

2022-10-06 10:34 UTC, maxime1907 commented on charts/topolvm/CHANGELOG.md
> +## [9.2.0] - 2022-10-05
okay

2022-10-06 10:34 UTC, maxime1907 commented on charts/topolvm/Chart.yaml
> +version: 9.2.0
okay

2022-10-06 10:35 UTC, maxime1907 commented on charts/topolvm/templates/controller/deployment.yaml
> -            {{- end }}
ah yes mb

2022-10-06 10:38 UTC, maxime1907 commented
> To update charts/topolvm/README.md, Could you run `make generate-helm-docs`?

done

2022-10-11 08:39 UTC, toshipp approved these changes

2022-10-11 09:52 UTC, daichimukai requested changes
Please fix typo in PR title as well.

2022-10-11 09:52 UTC, daichimukai commented on charts/topolvm/CHANGELOG.md
> +- feat: add `args` for `controller`, `node`, `scheduler`, `lvdm` to helm chart (#576)
```suggestion
- feat: add `args` for `controller`, `node`, `scheduler`, `lvmd` to helm chart (#576)
```

2022-10-11 11:22 UTC, maxime1907 commented
> Please fix typo in PR title as well.

done! @daichimukai

2022-10-12 00:42 UTC, toshipp approved these changes

2022-10-12 02:25 UTC, daichimukai approved these changes
LGTM

2022-10-12 02:25 UTC, merged