wip
topolvm/topolvm pull request #640
Opened 2023-01-10 15:03 UTC by bells17

2023-01-25 09:15 UTC, cupnes commented
@bells17 
I see the following statement in [the Design Detail of the proposal](https://github.com/topolvm/topolvm/blob/207f5148aedc04d4630f5c5e9ca1478edfd9d191/docs/proposals/lvcreate-option-on-storageclass.md#design-detail), is this implemented?

> The parameter value is passed to the topolvm-controller via CreateVolume RPC.

The current PR does not include the addition of parameters to the `CreateVolumeRequest` message, which is the argument of the `CreateVolume` RPC.

2023-01-25 09:19 UTC, toshipp commented
@cupnes 
I mean the value is embed in the parameter. He has already done it.
https://github.com/topolvm/topolvm/pull/640/files#diff-7b46685eeb2e24ed466c2d8f7c64f093cafa2b24e858407b1431c4d9e1576b47R38

2023-01-25 09:22 UTC, cupnes commented
@toshipp Thank you. I understood.

2023-01-26 04:51 UTC, cupnes requested changes

2023-01-26 08:15 UTC, llamerada-jp requested changes

2023-01-31 12:12 UTC, bells17 commented on charts/topolvm/Chart.yaml
> +version: 11.0.2
fixed it.

2023-01-31 12:13 UTC, bells17 commented on e2e/Makefile
>  		# We have only 5 VGs, but 6 PVs, since node-myvg4 uses both \
Thank you. I deleted these comments.

2023-01-31 12:14 UTC, bells17 commented
@cupnes @llamerada-jp Thank you for your review. I fixed the points that you commented on.
Would you review this again?

2023-02-01 00:54 UTC, llamerada-jp approved these changes

2023-02-01 07:00 UTC, cupnes approved these changes

2023-02-01 07:00 UTC, merged