Clarification of lock usage
topolvm/topolvm pull request #659
Opened 2023-02-17 13:50 UTC by toshipp

2023-02-22 08:55 UTC, llamerada-jp requested changes

2023-02-22 09:00 UTC, toshipp commented on driver/lock_test.go
> +}
Do you mean adding a test case to check `c` is closed properly after `UnlockByID`?

2023-02-24 08:14 UTC, llamerada-jp commented on driver/lock_test.go
> +}
Yes, I do.

2023-02-24 09:56 UTC, cupnes reviewed
Please some small fixes if you need them.

2023-02-24 09:56 UTC, cupnes commented on driver/node.go
> +// This is a wrapper for nodeServerNoLocked to protect concurrent method call.
```suggestion
// This is a wrapper for nodeServerNoLocked to protect concurrent method calls.
```

2023-02-24 09:56 UTC, cupnes commented on driver/node.go
> +	// We use a global lock because it assumes that each method does not take long time,
```suggestion
	// We use a global lock because it assumes that each method does not take a long time,
```

2023-02-28 00:25 UTC, llamerada-jp approved these changes

2023-02-28 00:57 UTC, cupnes approved these changes

2023-02-28 00:57 UTC, merged