Add container-structure-test
topolvm/topolvm pull request #664
Opened 2023-02-26 09:13 UTC by bells17

https://github.com/GoogleContainerTools/container-structure-test

2023-02-27 07:09 UTC, pluser commented on Makefile
> +.PHONY: container-stracture-test
```suggestion
.PHONY: container-structure-test
```

2023-02-27 08:39 UTC, daichimukai requested changes
Please squash to one commit.

2023-02-27 08:39 UTC, daichimukai commented on Makefile
> +container-stracture-test: ## Run container-structure-test.
```suggestion
container-structure-test: ## Run container-structure-test.
```

2023-02-27 08:39 UTC, daichimukai commented on .github/workflows/main.yaml
> +      - run: make container-stracture-test STRUCTURE_TEST_TARGET=${{ matrix.image }}
```suggestion
      - run: make container-structure-test STRUCTURE_TEST_TARGET=${{ matrix.image }}
```

2023-02-27 16:19 UTC, bells17 commented on Makefile
> +.PHONY: container-stracture-test
I fixed it.

2023-02-27 16:19 UTC, bells17 commented on .github/workflows/main.yaml
> +      - run: make container-stracture-test STRUCTURE_TEST_TARGET=${{ matrix.image }}
I fixed it.

2023-02-27 16:20 UTC, bells17 commented on Makefile
> +container-stracture-test: ## Run container-structure-test.
I fixed it.

2023-02-28 01:52 UTC, daichimukai approved these changes

2023-02-28 01:59 UTC, pluser approved these changes

2023-02-28 01:59 UTC, merged