Refactor getting objects
topolvm/topolvm pull request #679
Opened 2023-03-17 09:41 UTC by toshipp

see commit messages.

2023-03-24 08:03 UTC, toshipp commented on e2e/clone_test.go
> +			stdout, err := kubectl("exec", "-n", nsCloneTest, thinClonePodName, "--", "cat", writePath)
If the pod and the pvc are not ready, exec will be failed, so the checks are not needed.

2023-03-24 08:22 UTC, toshipp commented on e2e/helper_test.go
> -			_, _, err = kubectl("get", "node", "-o", "json")
Because getting node is done in getNodeAnnotationMapWithPrefix, it is not needed here.

2023-03-24 08:25 UTC, toshipp commented on e2e/scheduler_test.go
> -			if len(podlist.Items) == 0 {
getObjects returns error if podlist is empty, so this is not needed.

2023-03-28 10:28 UTC, llamerada-jp requested changes
reivew in progress 50%

2023-03-28 10:28 UTC, llamerada-jp commented on e2e/e2e_test.go
> +				return fmt.Errorf("failed to get PVC. err: %v", err)
```suggestion
				return fmt.Errorf("failed to get PVC. err: %w", err)
```

2023-03-28 10:28 UTC, llamerada-jp commented on e2e/e2e_test.go
>  				return fmt.Errorf("failed to get pv/%s. err: %v", volName, err)
```suggestion
				return fmt.Errorf("failed to get pv/%s. err: %w", volName, err)
```

2023-03-28 10:28 UTC, llamerada-jp commented on e2e/e2e_test.go
>  				return fmt.Errorf("failed to get volume size. err: %v", err)
```suggestion
				return fmt.Errorf("failed to get volume size. err: %w", err)
```

2023-03-28 10:28 UTC, llamerada-jp commented on e2e/e2e_test.go
>  				return fmt.Errorf("failed to get volume size. err: %v", err)
```suggestion
				return fmt.Errorf("failed to get volume size. err: %w", err)
```

2023-03-28 10:28 UTC, llamerada-jp commented on e2e/e2e_test.go
>  				return fmt.Errorf("failed to get volume size. err: %v", err)
```suggestion
				return fmt.Errorf("failed to get volume size. err: %w", err)
```

2023-03-28 10:28 UTC, llamerada-jp commented on e2e/e2e_test.go
>  				return fmt.Errorf("failed to test. err: %v", err)
```suggestion
				return fmt.Errorf("failed to test. err: %w", err)
```

2023-03-28 10:28 UTC, llamerada-jp commented on e2e/e2e_test.go
>  				return fmt.Errorf("failed to get volume size. err: %v", err)
```suggestion
				return fmt.Errorf("failed to get volume size. err: %w", err)
```

2023-03-28 10:28 UTC, llamerada-jp commented on e2e/e2e_test.go
>  		return fmt.Errorf("failed to check mount point. err: %v", err)
```suggestion
		return fmt.Errorf("failed to check mount point. err: %w", err)
```

2023-03-28 10:28 UTC, llamerada-jp commented on e2e/e2e_test.go
> +		return "", fmt.Errorf("failed to create pod. err: %v", err)
```suggestion
		return "", fmt.Errorf("failed to create pod. err: %w", err)
```

2023-03-28 10:28 UTC, llamerada-jp commented on e2e/lvcreate_options_test.go
>  				return fmt.Errorf("failed to get PVC. err: %v", err)
```suggestion
				return fmt.Errorf("failed to get PVC. err: %w", err)
```

2023-03-28 10:28 UTC, llamerada-jp commented on e2e/lvcreate_options_test.go
>  				return fmt.Errorf("failed to get logicalvolume. err: %v", err)
```suggestion
				return fmt.Errorf("failed to get logicalvolume. err: %w", err)
```

2023-03-28 10:28 UTC, llamerada-jp commented on e2e/lvcreate_options_test.go
>  				return fmt.Errorf("failed to get logicalvolume. err: %v", err)
```suggestion
				return fmt.Errorf("failed to get logicalvolume. err: %w", err)
```

2023-03-28 10:28 UTC, llamerada-jp commented on e2e/multiple_vg_test.go
>  				return fmt.Errorf("failed to get pvc. err: %v", err)
```suggestion
				return fmt.Errorf("failed to get pvc. err: %w", err)
```

2023-03-28 10:28 UTC, llamerada-jp commented on e2e/multiple_vg_test.go
> +		err = getObjects(&logicalvolume, "logicalvolumes", "-n", "topolvm-system", volName)
```suggestion
		err = getObjects(&logicalvolume, "logicalvolumes", volName)
```

2023-03-28 11:17 UTC, daichimukai approved these changes

2023-03-28 11:17 UTC, daichimukai commented on e2e/e2e_test.go
> +			err = getObjects(&lv, "logicalvolumes", volumeName)
+1

2023-03-29 07:30 UTC, llamerada-jp requested changes

2023-03-29 09:45 UTC, toshipp commented on e2e/scheduler_test.go
> -			if len(podlist.Items) == 0 {
I use `--ignore-not-found` on getObjects. kubectl with the option seems to return an empty string rather than a json contains empty list.

2023-03-30 09:37 UTC, toshipp commented on e2e/multiple_vg_test.go
> +		err = getObjects(&logicalvolume, "logicalvolumes", "-n", "topolvm-system", volName)
fixed https://github.com/topolvm/topolvm/compare/f8312475ef162761a4291580875fc97f4f221c3c..869f18f6b0fe5eefe677385799dc2041165cc0d7

2023-04-03 04:59 UTC, llamerada-jp approved these changes

2023-04-05 01:19 UTC, daichimukai approved these changes

2023-04-05 01:19 UTC, merged