feat(chart): allow livenessprobe configuration
topolvm/topolvm pull request #709
Opened 2023-06-19 13:46 UTC by maxime1907

2023-06-20 08:46 UTC, toshipp requested changes

2023-06-20 08:46 UTC, toshipp commented on charts/topolvm/Chart.yaml
> +version: 11.3.0
We separate code modification from releases. Please revert it.

2023-06-20 08:46 UTC, toshipp commented on charts/topolvm/templates/lvmd/daemonset.yaml
> +            failureThreshold: {{ .Values.livenessProbe.csi_registrar.failureThreshold }}
This container is lvmd. 
```suggestion
            failureThreshold: {{ .Values.livenessProbe.lvmd.failureThreshold }}
```

2023-06-20 11:58 UTC, maxime1907 commented on charts/topolvm/templates/lvmd/daemonset.yaml
> +            failureThreshold: {{ .Values.livenessProbe.csi_registrar.failureThreshold }}
my bad

2023-06-21 09:53 UTC, toshipp commented on charts/topolvm/values.yaml
Personally, I think that the values defined by Kubernetes should not be written. But that is not a major objection.

2023-06-21 11:35 UTC, maxime1907 commented on charts/topolvm/values.yaml
every popular chart lets us configure these parameters because depending on cluster loads, they may differ from defaults.

you can take a look at bitnami charts for instance:
 -https://github.com/bitnami/charts/blob/main/bitnami/apache/values.yaml

2023-06-26 07:44 UTC, toshipp commented on charts/topolvm/values.yaml
I mean we need not write values that are the same as kubernetes default but write a blank field.
For example, `failureThreshold` is 3 in default, so leave it to brank instead of specifying 3.
In templates, use `with` or `if` to render the value if it is specified.

2023-06-26 09:37 UTC, maxime1907 commented on charts/topolvm/values.yaml
oh okay i didnt understand what you meant, gonna change it

2023-06-27 08:35 UTC, toshipp approved these changes

2023-06-27 08:59 UTC, llamerada-jp approved these changes

2023-06-27 08:59 UTC, merged