feat: Allow adding custom labels to topolvm-controller and topolvm-no…
topolvm/topolvm pull request #734
Opened 2023-08-07 18:20 UTC by kvalliyurnatt

This PR enables additional labels to be set through helm on the topolvm controller and node pods.
This addresses: [issue-733](https://github.com/topolvm/topolvm/issues/733)

2023-08-09 05:13 UTC, satoru-takeuchi requested changes

2023-08-09 05:13 UTC, satoru-takeuchi commented on charts/topolvm/README.md
> +| controller.additionalLabels | object | `{}` | Additional labels to be set on the controller pod |
Could you also add `lvmd.additionalLabels` and `scheduler.additionalLabels`? These parameters would be helpful for someone.

2023-08-09 08:39 UTC, toshipp submitted a review, later dismissed

2023-08-09 21:46 UTC, satoru-takeuchi approved these changes

2023-08-10 01:07 UTC, toshipp approved these changes

2023-08-10 01:08 UTC, merged