fix: pin setup-envtest to go 1.20 before TopoLVM migrates to go 1.21
topolvm/topolvm pull request #865
Opened 2024-03-22 15:22 UTC by jakobmoellerdev

Attempts to temporarily fix #864 by pinning envtest to a version that didnt have the x.y.z syntax

2024-03-25 04:42 UTC, daichimukai commented on Makefile
>  	# Follow the official documentation to install the `latest` version, because explicitly specifying the version will get an error.
@llamerada-jp 
According to `git blame` you had wrote this comment. Do you remember what's meant by "explicitly specifying the version will get an error"? Is it safe to change this to specify concrete version?

2024-03-26 08:10 UTC, daichimukai commented on Makefile
>  	# Follow the official documentation to install the `latest` version, because explicitly specifying the version will get an error.
Understood. Thank you.

2024-03-26 08:21 UTC, daichimukai requested changes

2024-03-26 08:21 UTC, daichimukai commented on Makefile
> +	GOBIN=$(BINDIR) go install sigs.k8s.io/controller-runtime/tools/setup-envtest@bf15e44028f908c790721fc8fe67c7bf2d06a611
To improve dependency upgrade task efficiency, we keep dependency versions in the `versions.mk` file. Please add this version to there.

2024-03-26 08:21 UTC, daichimukai commented on Makefile
>  	# Follow the official documentation to install the `latest` version, because explicitly specifying the version will get an error.
Let's remove this comment. We cannot use the "latest" for a while, and I don't see any reason to avoid specifying hash as long as it works.

2024-03-27 05:58 UTC, llamerada-jp approved these changes

2024-03-27 06:11 UTC, daichimukai approved these changes
LGTM. Thanks @jakobmoellerdev.

2024-03-27 06:11 UTC, merged