chore: use exposed controller functions in topolvm controllers
topolvm/topolvm pull request #878
Opened 2024-04-08 15:11 UTC by jakobmoellerdev

In retrospect of https://github.com/topolvm/topolvm/pull/875 I noticed that everytime we add a field, we also have to export all embedded fields with it to work correctly outside of the topolvm package. This makes going back and forth for every field extremely tedious.

I thus changed the current command runners in TopoLVM to use the pkg variants of the runners. This will not change any logic (we were already using the same logic just with internal imports) but will let us know via compiler error whenever we have a field change that needs to be exported as well.

2024-04-09 01:27 UTC, toshipp requested changes

2024-04-09 01:27 UTC, toshipp commented on cmd/topolvm-node/app/run.go
>  		command.Containerized = true
This can be deleted.

2024-04-10 00:08 UTC, daichimukai approved these changes

2024-04-10 00:45 UTC, toshipp approved these changes

2024-04-10 00:45 UTC, merged