docs: add a note explaining the need for `topolvm.io/webhook=ignore`
topolvm/topolvm pull request #920
Opened 2024-05-20 08:55 UTC by cupnes

In getting started, it is not clear why `topolvm.io/webhook=ignore` is needed. Add a note explaining it.

Closes: https://github.com/topolvm/topolvm/issues/907

2024-05-23 00:57 UTC, ushitora-anqou requested changes
I feel that this description is a bit obscure. How about something like this?


> The label `topolvm.io/webhook=ignore` is set here to prevent the triggering of TopoLVM's mutating webhooks when pods and pvcs are created in the topolvm-system and kube-system namespaces. These webhooks depend on the topolvm-controller. Therefore, the webhooks should not be activated during TopoLVM's startup process to avoid causing it to become stuck.

2024-05-23 09:47 UTC, cupnes commented
@ushitora-anqou 
Thank you. It looks good, I will use it.

2024-05-24 00:23 UTC, ushitora-anqou approved these changes

2024-05-24 06:40 UTC, pluser approved these changes

2024-05-24 06:40 UTC, merged