Support Kubernetes 1.30
topolvm/topolvm pull request #928
Opened 2024-06-26 08:26 UTC by peng225

issue: https://github.com/topolvm/topolvm/issues/891

Signed-off-by: Shinya Hayashi <shinya-hayashi@cybozu.co.jp>

2024-06-26 09:35 UTC, peng225 commented on test/e2e/e2e_test.go
> +					Fail(fmt.Sprintf("unexpected VolumeResizeFailed event: %s", item.Message))
Now we may not need to iterate over `events.Items`.

2024-06-28 01:10 UTC, llamerada-jp requested changes

2024-06-28 01:11 UTC, toshipp submitted a review, later dismissed

2024-06-28 01:32 UTC, peng225 commented on versions.mk
> +CERT_MANAGER_VERSION := v1.14.7
Thanks, I changed the version.

2024-06-28 05:02 UTC, toshipp approved these changes

2024-06-28 08:27 UTC, llamerada-jp approved these changes

2024-06-28 08:27 UTC, merged