chore: move btrfs to beta
topolvm/topolvm pull request #935
Opened 2024-07-09 09:25 UTC by jakobmoellerdev

Partially resolves #876 and moves it into beta. We intend to keep it there for at least 2 releases, after which it will graduate

2024-07-10 00:01 UTC, satoru-takeuchi submitted a review, later dismissed

2024-07-10 00:34 UTC, cupnes requested changes
Could you also update the following line?

https://github.com/topolvm/topolvm/blob/48227afbe2b5d4beaf6ecb85fe383b749f6a167a/docs/advanced-setup.md?plain=1#L23

2024-07-11 00:11 UTC, cupnes approved these changes

2024-07-11 00:33 UTC, satoru-takeuchi approved these changes

2024-07-11 00:33 UTC, merged