test: enable goconst linter
topolvm/topolvm pull request #942
Opened 2024-07-24 10:10 UTC by llamerada-jp

issue: #853

2024-07-24 13:29 UTC, jakobmoellerdev requested changes
I have my doubts about this linter implementation. I dont think all the changes here are good for maintenance. Waiting for other opinions.

2024-07-24 13:29 UTC, jakobmoellerdev commented on test/e2e/clone_test.go
> +			_, err := kubectl("exec", "-n", nsCloneTest, "thinpod", "--", "cp", "/var/log/bootstrap.log", "/test1/bootstrap.log")
I think this change is actually bad, and if a linter flags this, we should not adopt it like this.

2024-07-24 13:29 UTC, jakobmoellerdev commented on test/e2e/thin_provisioning_test.go
> +			i := i
redundant scoped idx

2024-07-24 13:29 UTC, jakobmoellerdev commented on test/e2e/thin_provisioning_test.go
> +			i := i
redundant scoped idx

2024-07-24 13:29 UTC, jakobmoellerdev commented on internal/lvmd/lvservice_test.go
> +const (
these consts should be function scope not global scope

2024-07-25 08:07 UTC, cupnes approved these changes

2024-07-25 08:25 UTC, ushitora-anqou approved these changes
The current (fixed) version looks good to me.

2024-07-25 11:24 UTC, jakobmoellerdev approved these changes
lgtm

2024-07-26 00:14 UTC, merged