Add helm.sh/resource-policy annotation for CRD
topolvm/topolvm pull request #971
Opened 2024-10-03 19:48 UTC by jurim76

Prevent helm from uninstalling the CRD when the helm release is uninstalled.

2024-10-04 00:04 UTC, daichimukai requested changes

2024-10-04 00:04 UTC, daichimukai commented on charts/topolvm/values.yaml
> +crds:
When editing `values.yaml` file, we should update `charts/topolvm/README.md` by `make generate-helm-docs`.

```diff
$ make generate-helm-docs
./bin/helm-docs -c charts/topolvm/
INFO[2024-10-04T08:58:00+09:00] Found Chart directories [., charts/cert-manager]
INFO[2024-10-04T08:58:00+09:00] Generating README Documentation for chart charts/topolvm/charts/cert-manager
INFO[2024-10-04T08:58:00+09:00] Generating README Documentation for chart charts/topolvm
$ git diff
diff --git a/charts/topolvm/README.md b/charts/topolvm/README.md
index d5e5beaee448..7435e442ccdc 100644
--- a/charts/topolvm/README.md
+++ b/charts/topolvm/README.md
@@ -40,6 +40,7 @@ See [Getting Started](https://github.com/topolvm/topolvm/blob/topolvm-chart-v15.
 | controller.tolerations | list | `[]` | Specify tolerations. # ref: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/ |
 | controller.updateStrategy | object | `{}` | Specify updateStrategy. |
 | controller.volumes | list | `[{"emptyDir":{},"name":"socket-dir"}]` | Specify volumes. |
+| crds.keep | bool | `true` |  |
 | env.csi_provisioner | list | `[]` | Specify environment variables for csi_provisioner container. |
 | env.csi_registrar | list | `[]` | Specify environment variables for csi_registrar container. |
 | env.csi_resizer | list | `[]` | Specify environment variables for csi_resizer container. |
$ 
```

2024-10-04 00:04 UTC, daichimukai commented on charts/topolvm/values.yaml
> +  # This option makes it so that the "helm.sh/resource-policy": keep
This comment should be prefixed with `crds.keep -- ` so that it also appears as the comment in the generated `charts/topolvm/README.md`.

2024-10-12 10:47 UTC, jurim76 commented on charts/topolvm/templates/crds/topolvm.cybozu.com_logicalvolumes.yaml
@daichimukai 

Could I add this block
```
{{- if .Values.crds.keep }}                                                                                                                                        
helm.sh/resource-policy: keep                                                                                       
{{- end }}   
```
to  `config/crd/bases/topolvm.cybozu.com_logicalvolumes.yaml` and `config/crd/bases/topolvm.io_logicalvolumes.yaml` files directly?

2024-10-15 02:36 UTC, daichimukai commented on charts/topolvm/templates/crds/topolvm.cybozu.com_logicalvolumes.yaml
No, these files should be kept as valid yaml files which can be applied directly to Kubernetes clusters. We should inject the block when generating files under the `chart` directory. Unfortunately there exists no such trick now, so we need introduce new ones replacing simple `printf`. Some ideas (haven't tried though, thanks to @toshipp):

- Kustomize might allow us such a trick.
- Use yq.
  - I'm not sure whether this works. Is the helm's template block valid yaml?
- Use sed.
  - It seems that there's no difficulty in this way, but it might be hard to maintain. I'd like to avoid this if possible.
- The controller-tools may have a helper tool.

2024-10-16 19:06 UTC, jurim76 commented on charts/topolvm/templates/crds/topolvm.cybozu.com_logicalvolumes.yaml
Not sure about kustomize, I could patch resources with kustomize for sure, but this method is out-of-scope, imho (I'd rather create the custom helm chart)
Yq is not included in base packages of most linux distributions, so you need to install yq separately, afaik.
Also there are two versions of yq - https://pypi.org/project/yq/ and https://github.com/mikefarah/yq and this may get confused.
Sed included in all linux distributions by default and my block could be easily inserted with sed (Makefile is already using sed command)

2024-11-10 19:53 UTC, closed without merging